name: Build and Deploy Docker Image with Version Tag

on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_IMAGE: ghcr.io/dhanuprys/entreprenix # Your GHCR organization image
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          # Use the Git tag as the version tag for Docker image
          VERSION_TAG=${GITHUB_REF#refs/tags/}  # Extract tag name without refs/tags/
          echo "Building Docker image with version: $VERSION_TAG"

          # Build and tag the image with the version tag
          docker build -t $DOCKER_IMAGE:$VERSION_TAG .

          # Optionally, tag as latest if desired
          docker tag $DOCKER_IMAGE:$VERSION_TAG $DOCKER_IMAGE:latest

      - name: Push Docker Image
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}  # Extract tag name
          # Push the tagged image to GHCR
          docker push $DOCKER_IMAGE:$VERSION_TAG

          # Push the 'latest' tag (optional)
          docker push $DOCKER_IMAGE:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Deployment script
            cd /opt/app/dedan/entreprenix
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }}
            docker compose pull
            docker compose up -d --force-recreate
            docker system prune -af
